upgade from ubuntu 12.04 to 14.04 and publish pdf builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,3 +1,5 @@
+dist: trusty
+
 language: python
 
 matrix:
@@ -18,12 +20,15 @@ install:
       yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots;
       yes | sudo add-apt-repository ppa:gstreamer-developers/ppa;
       sudo apt-get update;
-      sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev;
-      sudo apt-get install libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-plugins-base;
-      sudo apt-get install python-dev libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libX11-dev libmtdev-dev;
-      sudo apt-get install python-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev;
-      sudo apt-get install xvfb pulseaudio;
+      sudo apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev;
+      sudo apt-get -y install libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-plugins-base;
+      sudo apt-get -y install python-dev libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libX11-dev libmtdev-dev;
+      sudo apt-get -y install python-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev;
+      sudo apt-get -y install xvfb pulseaudio;
       pip install --upgrade cython pillow nose coveralls;
+    fi;
+  - if [ "${RUN}" == "docs" ]; then
+      sudo apt-get -y install texlive-full;
       pip install --upgrade sphinxcontrib-blockdiag sphinxcontrib-seqdiag sphinxcontrib-actdiag sphinxcontrib-nwdiag;
     fi;
 
@@ -35,7 +40,7 @@ before_script:
     fi;
 
 script:
-  - set -ev
+  - set -v
   - if [ "${RUN}" == "unit" ]; then
       make;
       make test;
@@ -48,6 +53,8 @@ script:
     fi;
   - if [ "${RUN}" == "docs" ]; then
       make html;
+      make pdf || true;  # first attempt may fail
+      make pdf;
     fi;
 
 after_success:
@@ -56,6 +63,8 @@ after_success:
       chmod 600 ~/.ssh/id_rsa;
       echo -e "Host kivy.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config;
       rsync --delete --force -r -e ssh ./doc/build/html/ kivy@kivy.org:~/kivy.org/docs/api-trunk/;
+      mv ./doc/build/latex/Kivy.pdf ./doc/build/latex/Kivy-latest.pdf;
+      rsync --delete --force -e ssh ./doc/build/latex/Kivy-latest.pdf kivy@kivy.org:~/kivy.org/docs/pdf/Kivy-latest.pdf;
     fi;
 
 notifications:
